/*
# Seed Categories and Menu Items

## Overview
Inserts all 9 menu categories and all menu items from the VERO VITO menu specification.
No prices, no images — both are added later via the Admin Dashboard.

## Categories inserted (in order):
1. Fresh Cut Fruits
2. Avocado Cocktails
3. Cocktails & Fresh Juices
4. Iced Coffee
5. Milkshake
6. Mojitos
7. Coffee & Hot Drinks
8. Breakfast and Bowls
9. Desserts

## Menu Items
All items from the specification are inserted with English and Arabic names/descriptions.
Where the spec only provided English, the Arabic name matches the English name (transliteration
or direct translation), and description_ar is the same as description_en where no Arabic was provided.
*/

-- ============ CATEGORIES ============
INSERT INTO categories (name_en, name_ar, sort_order, is_enabled) VALUES
('Fresh Cut Fruits', 'فواكه طازجة مقطعة', 1, true),
('Avocado Cocktails', 'كوكتيلات الأفوكادو', 2, true),
('Cocktails & Fresh Juices', 'كوكتيلات وعصائر طازجة', 3, true),
('Iced Coffee', 'قهوة مثلجة', 4, true),
('Milkshake', 'ميلك شيك', 5, true),
('Mojitos', 'موهيتو', 6, true),
('Coffee & Hot Drinks', 'قهوة ومشروبات ساخنة', 7, true),
('Breakfast and Bowls', 'فطور وبولز', 8, true),
('Desserts', 'حلويات', 9, true)
ON CONFLICT DO NOTHING;

-- Helper: get category IDs
DO $$
DECLARE
  cat_fruits uuid; cat_avocado uuid; cat_cocktails uuid; cat_iced uuid;
  cat_milkshake uuid; cat_mojitos uuid; cat_coffee uuid; cat_breakfast uuid; cat_desserts uuid;
BEGIN
  SELECT id INTO cat_fruits FROM categories WHERE name_en = 'Fresh Cut Fruits';
  SELECT id INTO cat_avocado FROM categories WHERE name_en = 'Avocado Cocktails';
  SELECT id INTO cat_cocktails FROM categories WHERE name_en = 'Cocktails & Fresh Juices';
  SELECT id INTO cat_iced FROM categories WHERE name_en = 'Iced Coffee';
  SELECT id INTO cat_milkshake FROM categories WHERE name_en = 'Milkshake';
  SELECT id INTO cat_mojitos FROM categories WHERE name_en = 'Mojitos';
  SELECT id INTO cat_coffee FROM categories WHERE name_en = 'Coffee & Hot Drinks';
  SELECT id INTO cat_breakfast FROM categories WHERE name_en = 'Breakfast and Bowls';
  SELECT id INTO cat_desserts FROM categories WHERE name_en = 'Desserts';

  -- ============ FRESH CUT FRUITS ============
  INSERT INTO menu_items (category_id, name_en, name_ar, description_en, description_ar, sort_order) VALUES
  (cat_fruits, 'Fresh Strawberry Pieces', 'قطع فراولة طازجة', 'Fresh strawberries, carefully washed and cut into evenly sized pieces, boasting a delicious sweet and tangy flavor, perfect as a healthy snack.', 'فراولة طازجة، مغسولة بعناية ومقطعة لقطع متساوية الحجم، بطعم حلو ولاذع لذيذ، مثالية كوجبة خفيفة صحية.', 1),
  (cat_fruits, 'Strawberry Pieces with Chocolate', 'قطع فراولة بالشوكولاتة', 'Carefully selected fresh strawberry pieces covered with a rich and delicious creamy chocolate layer, combining the natural sweetness of strawberries with the luxurious taste of chocolate.', 'قطع فراولة طازجة مختارة بعناية مغطاة بطبقة شوكولاتة كريمية غنية ولذيذة، تجمع بين حلاوة الفراولة الطبيعية وطعم الشوكولاتة الفاخر.', 2),
  (cat_fruits, 'Fresh Strawberry and Kiwi Slices', 'شرائح فراولة وكيوي طازجة', 'Carefully cut fresh strawberry and kiwi slices, providing a delicious blend of sweet and tangy flavors with vibrant colors and high nutritional benefits.', 'شرائح فراولة وكيوي طازجة مقطعة بعناية، تقدم مزيجاً لذيذاً من النكهات الحلوة واللاذعة بألوان زاهية وفوائد غذائية عالية.', 3),
  (cat_fruits, 'Strawberry and Kiwi Slices with Chocolate', 'شرائح فراولة وكيوي بالشوكولاتة', 'Freshly cut strawberry and kiwi slices, carefully coated with a rich layer of dark chocolate, combining the natural sweetness of fruit with the luxurious taste of chocolate.', 'شرائح فراولة وكيوي مقطعة طازجة، مغطاة بعناية بطبقة غنية من الشوكولاتة الداكنة، تجمع بين حلاوة الفاكهة الطبيعية وطعم الشوكولاتة الفاخر.', 4),
  (cat_fruits, 'Banana Slices with Chocolate', 'شرائح موز بالشوكولاتة', 'Fresh banana slices carefully cut and covered with a rich and delicious layer of chocolate, combining the natural sweetness of bananas with the luxurious taste of chocolate.', 'شرائح موز طازجة مقطعة بعناية ومغطاة بطبقة غنية ولذيذة من الشوكولاتة، تجمع بين حلاوة الموز الطبيعية وطعم الشوكولاتة الفاخر.', 5),
  (cat_fruits, 'Fresh Cut Watermelon', 'بطيخ مقطع طازج', 'Fresh watermelon, carefully cut daily, preserving its natural sweet and juicy flavor. Served chilled and ready to enjoy as a refreshing snack.', 'بطيخ طازج، يقطع بعناية يومياً، مع الحفاظ على نكهته الطبيعية الحلوة والعصيرية. يقدم بارداً وجاهزاً للاستمتاع به كوجبة خفيفة منعشة.', 6);

  -- ============ AVOCADO COCKTAILS ============
  INSERT INTO menu_items (category_id, name_en, name_ar, description_en, description_ar, sort_order) VALUES
  (cat_avocado, 'Avocado Special', 'أفوكادو خاص', 'Fresh avocado mixed with rich milk, natural honey, selected nuts, and a layer of creamy local cream for a healthy and delicious drink.', 'أفوكادو طازج مخلوط مع حليب غني، عسل طبيعي، مكسرات مختارة، وطبقة من القشطة الكريمية المحلية لمشروب صحي ولذيذ.', 1),
  (cat_avocado, 'Fresh Avocado', 'أفوكادو طازج', 'Fresh and nutrient-rich avocado juice made from ripe avocado fruit, blended with milk and honey for a creamy, delicious, and healthy taste.', 'عصير أفوكادو طازج وغني بالعناصر الغذائية مصنوع من ثمرة أفوكادو ناضجة، مخلوط مع الحليب والعسل لطعم كريمي لذيذ وصحي.', 2),
  (cat_avocado, 'Avocado and Banana', 'أفوكادو وموز', 'A delicious creamy drink combining fresh avocado, ripe banana, and cold milk in a refreshing and nutrient-rich blend.', 'مشروب كريمي لذيذ يجمع بين الأفوكادو الطازج، الموز الناضج، والحليب البارد في مزيج منعش وغني بالعناصر الغذائية.', 3),
  (cat_avocado, 'Avocado and Mango', 'أفوكادو ومانجو', 'A refreshing drink combining creamy avocado and sweet mango with fresh milk and natural honey for a rich and healthy taste.', 'مشروب منعش يجمع بين الأفوكادو الكريمي والمانجو الحلوة مع الحليب الطازج والعسل الطبيعي لطعم غني وصحي.', 4),
  (cat_avocado, 'Avocado and Strawberry', 'أفوكادو وفراولة', 'A refreshing drink combining creamy avocado and fresh strawberries with smooth milk and natural honey for a delicious taste rich in health benefits.', 'مشروب منعش يجمع بين الأفوكادو الكريمي والفراولة الطازجة مع حليب سلس وعسل طبيعي لطعم لذيذ غني بالفوائد الصحية.', 5),
  (cat_avocado, 'Avocado with Pomegranate', 'أفوكادو مع رمان', 'A refreshing drink combining smooth avocado cream with the delicious tartness of pomegranate, with a touch of natural honey and cold ice cubes.', 'مشروب منعش يجمع بين كريمة الأفوكادو السلسة مع اللاذعة اللذيذة للرمان، مع لمسة من العسل الطبيعي ومكعبات الثلج الباردة.', 6);

  -- ============ COCKTAILS & FRESH JUICES ============
  INSERT INTO menu_items (category_id, name_en, name_ar, description_en, description_ar, sort_order) VALUES
  (cat_cocktails, 'Firo Tropical Cocktail', 'كوكتيل فيرو الاستوائي', 'Fresh tropical fruit juice prepared daily from the finest carefully selected fruits, combining the flavors of pineapple, mango, passion fruit, and coconut for a delightful experience.', 'عصير فواكه استوائية طازج يُحضّر يومياً من أجود الفواكه المختارة بعناية، يجمع بين نكهات الأناناس والمانجو والباذنجان وجوز الهند لتجربة ممتعة.', 1),
  (cat_cocktails, 'Fresh Orange and Banana', 'برتقال وموز طازج', 'Fresh and delicious juice made from natural oranges and bananas, combining the sweetness of bananas with the refreshing tang of oranges. A healthy drink rich in vitamins.', 'عصير طازج ولذيذ مصنوع من البرتقال والموز الطبيعي، يجمع بين حلاوة الموز ونعومة البرتقال. مشروب صحي غني بالفيتامينات.', 2),
  (cat_cocktails, 'Mango and Strawberry', 'مانجو وفراولة', 'A fresh and delicious juice made from ripe mangoes and fresh red strawberries. A refreshing blend that combines natural sweetness with a distinct fruity flavor, perfect at any time.', 'عصير طازج ولذيذ مصنوع من المانجو الناضجة والفراولة الحمراء الطازجة. مزيج منعش يجمع بين الحلاوة الطبيعية ونكهة فاكهة مميزة، مثالي في أي وقت.', 3),
  (cat_cocktails, 'Strawberry with Lemon and Mint', 'فراولة مع ليمون ونعناع', 'Fresh strawberry juice mixed with tart lemon juice and refreshing mint flavor, served iced for a completely natural and refreshing experience.', 'عصير فراولة طازج مخلوط مع عصير ليمون لاذع ونكهة النعناع المنعشة، يقدم مثلجاً لتجربة طبيعية ومنعشة تماماً.', 4),
  (cat_cocktails, 'Fresh Lemonade', 'ليموناضة طازجة', 'Refreshing lemonade made from the finest fresh lemons with fine sugar and cold water, served chilled to give you a delicious refreshment with every sip.', 'ليموناضة منعشة مصنوعة من أجود الليمون الطازج مع سكر ناعم وماء بارد، تقدم باردة لمنحك انتعاشاً لذيذاً مع كل رشفة.', 5),
  (cat_cocktails, 'Fresh Brazilian Lemonade', 'ليموناضة برازيلية طازجة', 'Refreshing Brazilian lemonade made from the finest fresh lemons with sugar, sweetened condensed milk, and cold water, served chilled to give you a summer refreshment.', 'ليموناضة برازيلية منعشة مصنوعة من أجود الليمون الطازج مع السكر والحليب المكثف المحلى والماء البارد، تقدم باردة لمنحك انتعاشاً صيفياً.', 6),
  (cat_cocktails, 'Pomegranate and Pineapple', 'رمان وananas', 'A refreshing blend of antioxidant-rich pomegranate juice and sweet tropical pineapple juice, served cold with ice for a delicious and refreshing experience.', 'مزيج منعش من عصير الرمان الغني بمضادات الأكسدة وعصير الأناناس الاستوائي الحلو، يقدم بارداً مع الثلج لتجربة لذيذة ومنعشة.', 7),
  (cat_cocktails, 'Orange and Passion Fruit', 'برتقال وباذنجان', 'A refreshing natural juice combining the sweetness of fresh orange with the appetizing tang of passion fruit. A healthy drink rich in important vitamins and nutrients.', 'عصير طبيعي منعش يجمع بين حلاوة البرتقال الطازج مع اللاذعة الشهية للباذنجان. مشروب صحي غني بالفيتامينات والعناصر الغذائية المهمة.', 8),
  (cat_cocktails, 'Guava and Strawberry', 'جوافة وفراولة', 'A refreshing fresh juice that combines the sweetness of tropical guava with the delicious tangy taste of strawberry, served cold with ice cubes.', 'عصير طازج منعش يجمع بين حلاوة الجوافة الاستوائية مع الطعم اللاذع اللذيذ للفراولة، يقدم بارداً مع مكعبات الثلج.', 9),
  (cat_cocktails, 'Guava and Mango', 'جوافة ومانجو', 'A delicious tropical blend of fresh guava and ripe mango, combining natural sweetness with rich flavors. A refreshing and healthy drink perfect for any time of day.', 'مزيج استوائي لذيذ من الجوافة الطازجة والمانجو الناضجة، يجمع بين الحلاوة الطبيعية والنكهات الغنية. مشروب منعش وصحي مثالي لأي وقت من اليوم.', 10),
  (cat_cocktails, 'Guava and Passion Fruit', 'جوافة وباذنجان', 'An exceptional blend of fresh guava and aromatic passion fruit, combining natural sweetness and refreshing tartness with a unique tropical flavor, served chilled.', 'مزيج استثنائي من الجوافة الطازجة والباذنجان العطري، يجمع بين الحلاوة الطبيعية واللاذعة المنعشة بنكهة استوائية فريدة، يقدم بارداً.', 11),
  (cat_cocktails, 'Guava and Pineapple', 'جوافة وأناناس', 'A refreshing natural juice combining the sweetness of tropical guava and the delicious tanginess of pineapple, served cold with ice cubes.', 'عصير طبيعي منعش يجمع بين حلاوة الجوافة الاستوائية واللاذعة اللذيذة للأناناس، يقدم بارداً مع مكعبات الثلج.', 12),
  (cat_cocktails, 'Guava and Orange', 'جوافة وبرتقال', 'A refreshing fresh juice combining the sweetness of guava and the natural tartness of orange, served cold with ice cubes for a delicious refreshing experience.', 'عصير طازج منعش يجمع بين حلاوة الجوافة واللاذعة الطبيعية للبرتقال، يقدم بارداً مع مكعبات الثلج لتجربة منعشة لذيذة.', 13),
  (cat_cocktails, 'Guava and Pomegranate', 'جوافة ورمان', 'A refreshing fresh juice that combines the sweetness of tropical guava with the delicious tartness of pomegranate. A natural drink rich in vitamins and minerals, served cold for an incomparable refreshing experience.', 'عصير طازج منعش يجمع بين حلاوة الجوافة الاستوائية واللاذعة اللذيذة للرمان. مشروب طبيعي غني بالفيتامينات والمعادن، يقدم بارداً لتجربة منعشة لا تضاهى.', 14),
  (cat_cocktails, 'Galaxy', 'جالاكسي', 'A delicious Galaxy drink combining smooth ice cream, rich chocolate, fresh milk, and natural banana with a sprinkle of dark chocolate.', 'مشروب جالاكسي لذيذ يجمع بين الآيس كريم السلس، الشوكولاتة الغنية، الحليب الطازج، والموز الطبيعي مع رشة من الشوكولاتة الداكنة.', 15),
  (cat_cocktails, 'Kiwi, Pineapple, and Strawberry', 'كيوى وأناناس وفراولة', 'Fresh and delicious juice combining the tangy flavors of kiwi, tropical pineapple, and sweet strawberry. A refreshing blend rich in vitamins and minerals important for your health.', 'عصير طازج ولذيذ يجمع بين النكهات اللاذعة للكيوي والأناناس الاستوائي والفراولة الحلوة. مزيج منعش غني بالفيتامينات والمعادن المهمة لصحتك.', 16),
  (cat_cocktails, 'Fresh Red Watermelon', 'بطيخ أحمر طازج', 'Chilled fresh watermelon juice, prepared from the finest ripe red watermelons, served cold and refreshing.', 'عصير بطيخ أحمر طازج وبارد، محضّر من أجود البطيخ الأحمر الناضج، يقدم بارداً ومنعشاً.', 17),
  (cat_cocktails, 'Strawberry and Beetroot Juice', 'عصير فراولة وبنجر', 'A refreshing juice combining fresh, bright red strawberries and health-benefiting beetroot, served cold with ice cubes for a delicious refreshing experience.', 'عصير منعش يجمع بين الفراولة الطازجة الحمراء الزاهية والبنجر ذو الفوائد الصحية، يقدم بارداً مع مكعبات الثلج لتجربة منعشة لذيذة.', 18),
  (cat_cocktails, 'Kiwi', 'كيوي', 'Refreshing kiwi juice made from fresh kiwi fruit with ice and sugar to offer a delicious and healthy natural drink.', 'عصير كيوي منعش مصنوع من فاكهة الكيوي الطازجة مع الثلج والسكر لتقديم مشروب طبيعي لذيذ وصحي.', 19),
  (cat_cocktails, 'Fresh Kiwi and Mango', 'كيوي ومانجو طازج', 'A refreshing fresh juice combining the sweetness of golden mango and the refreshing tang of kiwi, with natural fruit pulp. Served chilled for a delicious and healthy experience.', 'عصير طازج منعش يجمع بين حلاوة المانجو الذهبية ونعومة الكيوي، مع لب الفاكهة الطبيعي. يقدم بارداً لتجربة لذيذة وصحية.', 20),
  (cat_cocktails, 'Fresh Orange and Carrot Juice', 'عصير برتقال وجزر طازج', 'Fresh and delicious juice made from natural oranges and carrots, combining sweetness with high health benefits. A refreshing drink rich in vitamins.', 'عصير طازج ولذيذ مصنوع من البرتقال والجزر الطبيعي، يجمع بين الحلاوة والفوائد الصحية العالية. مشروب منعش غني بالفيتامينات.', 21),
  (cat_cocktails, 'Pineapple, Mango, and Kiwi Juice', 'عصير أناناس ومانجو وكيوي', 'A refreshing fresh juice combining the tropical sweetness of pineapple, the richness of golden mango, and the tangy freshness of kiwi. A delicious blend rich in vitamins and nutrients.', 'عصير طازج منعش يجمع بين حلاوة الأناناس الاستوائية وغنى المانجو الذهبية ونعومة الكيوي. مزيج لذيذ غني بالفيتامينات والعناصر الغذائية.', 22),
  (cat_cocktails, 'Fresh Cantaloupe', 'شمام طازج', 'Sweet-scented fresh cantaloupe with soft orange flesh and juice rich in vitamins and minerals, served chilled or in a refreshing juice.', 'شمام طازج حلو الرائحة بلحم برتقالي ناعم وعصير غني بالفيتامينات والمعادن، يقدم بارداً أو كعصير منعش.', 23),
  (cat_cocktails, 'Cantaloupe with Fresh Milk', 'شمام مع حليب طازج', 'A refreshing drink combining the deliciousness of fresh cantaloupe with natural milk rich in calcium. A delightful blend served cold with ice cubes to give you a healthy refreshment and a wonderful taste.', 'مشروب منعش يجمع بين لذة الشمام الطازج مع الحليب الطبيعي الغني بالكالسيوم. مزيج لذيذ يقدم بارداً مع مكعبات الثلج لمنحك انتعاشاً صحياً وطعماً رائعاً.', 24),
  (cat_cocktails, 'Awar Qalb', 'أور قلب', 'A delicious blend of fresh mango and red strawberries with smooth vanilla ice cream, served as a refreshing and sweet drink, perfect for hot summer days.', 'مزيج لذيذ من المانجو الطازجة والفراولة الحمراء مع آيس كريم الفانيلا السلس، يقدم كمشروب منعش وحلو، مثالي لأيام الصيف الحارة.', 25),
  (cat_cocktails, 'Fresh Kiwi and Pineapple Mix', 'مزيج كيوي وأناناس طازج', 'Enjoy a refreshing blend of fresh kiwi and sweet pineapple, offering rich tropical flavors and a zesty acidity, with a smooth texture and authentic natural taste.', 'استمتع بمزيج منعش من الكيوي الطازج والأناناس الحلو، يقدم نكهات استوائية غنية وحموضة منعشة، بقوام سلس وطعم طبيعي أصيل.', 26),
  (cat_cocktails, 'Fresh Strawberry with Pomegranate', 'فراولة مع رمان طازج', 'A refreshing mix of bright red fresh strawberries with delicious pomegranate seeds, offering a natural juice rich in essential vitamins and minerals for your health.', 'مزيج منعش من الفراولة الطازجة الحمراء الزاهية مع بذور الرمان اللذيذة، يقدم عصيراً طبيعياً غنياً بالفيتامينات والمعادن الأساسية لصحتك.', 27),
  (cat_cocktails, 'Mango, Banana, and Milk', 'مانجو وموز وحليب', 'A refreshing juice combining ripe bananas, fresh milk, and sweet delicious mango, served cold with ice cubes for a refreshing and vitamin-rich experience.', 'عصير منعش يجمع بين الموز الناضج والحليب الطازج والمانجو الحلوة اللذيذة، يقدم بارداً مع مكعبات الثلج لتجربة منعشة وغنية بالفيتامينات.', 28),
  (cat_cocktails, 'Cocktail without added sugar', 'كوكتيل بدون سكر مضاف', 'A fresh and delicious fruit cocktail, a mix of carefully selected seasonal fruits without added processed sugars, a natural, healthy, and refreshing taste.', 'كوكتيل فواكه طازج ولذيذ، مزيج من الفواكه الموسمية المختارة بعناية بدون سكريات معالجة مضافة، طعم طبيعي وصحي ومنعش.', 29),
  (cat_cocktails, 'Natural Guava', 'جوافة طبيعية', 'Carefully selected fresh natural guava, seedless and packed with beneficial vitamins and nutrients, served refreshing and healthy.', 'جوافة طبيعية طازجة مختارة بعناية، بدون بذور وغنية بالفيتامينات والعناصر الغذائية المفيدة، تقدم منعشة وصحية.', 30),
  (cat_cocktails, 'Fresh Carrot Juice', 'عصير جزر طازج', 'Fresh carrot juice squeezed daily from the finest carefully selected carrots, rich in vitamins and beneficial nutrients for your health. A delicious and healthy natural taste.', 'عصير جزر طازج يعصر يومياً من أجود الجزر المختار بعناية، غني بالفيتامينات والعناصر الغذائية المفيدة لصحتك. طعم طبيعي لذيذ وصحي.', 31),
  (cat_cocktails, 'Mango and Passion Juice', 'عصير مانجو وباذنجان', 'A refreshing juice that combines the sweetness of tropical mango with the delicious tanginess of passion fruit. A healthy natural drink perfect for refreshment on hot days.', 'عصير منعش يجمع بين حلاوة المانجو الاستوائية واللاذعة اللذيذة للباذنجان. مشروب طبيعي صحي مثالي للانتعاش في الأيام الحارة.', 32),
  (cat_cocktails, 'Fero Cocktail', 'كوكتيل فيرو', 'A refreshing and natural drink made from the finest fresh fruits and natural juices, served cold with ice.', 'مشروب منعش وطبيعي مصنوع من أجود الفواكه الطازجة والعصائر الطبيعية، يقدم بارداً مع الثلج.', 33),
  (cat_cocktails, 'Banana and Milk', 'موز وحليب', 'A delicious blend of fresh, ripe bananas with cold milk, creating a creamy drink rich in important vitamins and nutrients, perfect for breakfast or as a snack.', 'مزيج لذيذ من الموز الطازج الناضج مع الحليب البارد، يخلق مشروباً كريمياً غنياً بالفيتامينات والعناصر الغذائية المهمة، مثالي للفطور أو كوجبة خفيفة.', 34),
  (cat_cocktails, 'Fresh Strawberry', 'فراولة طازجة', 'Fresh and delicious strawberry juice made from the finest ripe red strawberries, served chilled and refreshing.', 'عصير فراولة طازج ولذيذ مصنوع من أجود الفراولة الحمراء الناضجة، يقدم بارداً ومنعشاً.', 35),
  (cat_cocktails, 'Banana and Strawberry with Milk', 'موز وفراولة مع حليب', 'A refreshing blend of fresh bananas and ripe red strawberries with cold milk, offering a healthy, delicious drink rich in vitamins and nutrients.', 'مزيج منعش من الموز الطازج والفراولة الحمراء الناضجة مع الحليب البارد، يقدم مشروباً صحياً ولذيذاً غنياً بالفيتامينات والعناصر الغذائية.', 36),
  (cat_cocktails, 'Natural Egyptian Mango', 'مانجو مصرية طبيعية', 'Fresh natural mango juice made from the finest carefully selected ripe mangoes, boasting a sweet, rich taste and a delicious creamy texture.', 'عصير مانجو طبيعي طازج مصنوع من أجود المانجو الناضجة المختارة بعناية، بطعم حلو غني وقوام كريمي لذيذ.', 37),
  (cat_cocktails, 'Sliced Fruit Cocktail', 'كوكتيل فواكه مقطعة', 'A carefully sliced fresh fruit cocktail, filled with colorful fruit pieces, with extra pieces on top of the cup, garnished with smooth cream, golden honey drops, and a sprinkle of nuts.', 'كوكتيل فواكه طازجة مقطع بعناية، مليء بقطع فواكه ملونة، مع قطع إضافية فوق الكوب، مزين بكريمة سلسة وقطرات عسل ذهبية ورشة من المكسرات.', 38),
  (cat_cocktails, 'Kiwi and Lemon', 'كيوي وليمون', 'A refreshing juice combining the natural sweetness of kiwi with the vibrant acidity of lemon. A healthy drink rich in vitamins and minerals, served cold for an unforgettable refreshing experience.', 'عصير منعش يجمع بين حلاوة الكيوي الطبيعية وحموضة الليمون النابضة. مشروب صحي غني بالفيتامينات والمعادن، يقدم بارداً لتجربة منعشة لا تُنسى.', 39),
  (cat_cocktails, 'Vitamin C', 'فيتامين سي', 'A refreshing natural juice rich in vitamin C, combining the sweetness of oranges, the tartness of lemons, the unique flavor of kiwi, and the tropical sweetness of pineapple.', 'عصير طبيعي منعش غني بفيتامين سي، يجمع بين حلاوة البرتقال، لاذعة الليمون، نكهة الكيوي الفريدة، وحلاوة الأناناس الاستوائية.', 40),
  (cat_cocktails, 'Fresh Orange Juice', 'عصير برتقال طازج', 'Fresh orange juice, squeezed daily from the finest carefully selected oranges. It has a sweet, refreshing taste and is rich in Vitamin C, perfect for enjoying at any time of the day.', 'عصير برتقال طازج، يعصر يومياً من أجود البرتقال المختار بعناية. له طعم حلو منعش وغني بفيتامين سي، مثالي للاستمتاع في أي وقت من اليوم.', 41),
  (cat_cocktails, 'Lemon and Mint Juice', 'عصير ليمون ونعناع', 'A refreshing juice that combines fresh, sour lemon with aromatic mint to create a healthy and delicious drink, perfect for hot days.', 'عصير منعش يجمع بين الليمون الطازج الحامض والنعناع العطري لخلق مشروب صحي ولذيذ، مثالي للأيام الحارة.', 42),
  (cat_cocktails, 'Pomegranate and Beetroot Juice', 'عصير رمان وبنجر', 'This refreshing pomegranate and beetroot juice combines the natural sweetness of pomegranate with the rich benefits of beetroot. Served cold with ice cubes for a refreshing and healthy experience.', 'عصير الرمان والبنجر المنعش هذا يجمع بين حلاوة الرمان الطبيعية والفوائد الغنية للبنجر. يقدم بارداً مع مكعبات الثلج لتجربة منعشة وصحية.', 43),
  (cat_cocktails, 'Fresh Pomegranate Juice', 'عصير رمان طازج', 'Fresh pomegranate juice, rich in health benefits and antioxidants, served cold and refreshing with ice cubes for a delightful and healthy experience.', 'عصير رمان طازج، غني بالفوائد الصحية ومضادات الأكسدة، يقدم بارداً ومنعشاً مع مكعبات الثلج لتجربة لذيذة وصحية.', 44),
  (cat_cocktails, 'Special Farghali Mango', 'مانجو فرغلي الخاصة', 'Fresh Egyptian Farghali mango with a rich, distinctly sweet taste, served as a refreshing natural juice or a delicious cocktail that combines authentic flavor and refreshment.', 'مانجو فرغلي مصرية طازجة بطعم حلو غني ومميز، تقدم كعصير طبيعي منعش أو كوكتيل لذيذ يجمع بين النكهة الأصيلة والانتعاش.', 45);

  -- ============ ICED COFFEE ============
  INSERT INTO menu_items (category_id, name_en, name_ar, description_en, description_ar, sort_order) VALUES
  (cat_iced, 'Iced Coffee Latte', 'آيس كوفي لاتيه', 'Rich espresso coffee blended with cold milk and ice cubes to provide a refreshing and smooth drink with a deep and creamy coffee taste.', 'قهوة إسبريسو غنية مخلوطة مع الحليب البارد ومكعبات الثلج لتقديم مشروب منعش وسلس بطعم قهوة عميق وكريمي.', 1),
  (cat_iced, 'Iced Raspberry Latte', 'آيس راسببيري لاتيه', 'Iced latte coffee with the aroma of fresh red raspberries and smooth, creamy milk, giving you a delicious refreshment with every sip.', 'قهوة آيس لاتيه مع عبق التوت الأحمر الطازج والحليب السلس الكريمي، تمنحك انتعاشاً لذيذاً مع كل رشفة.', 2),
  (cat_iced, 'Iced Spanish Latte', 'آيس سبانيش لاتيه', 'Refreshing iced Spanish latte made with strong espresso, fresh milk, and sweetened condensed milk, enhanced with a special Italian blend, served iced for a unique and delicious experience.', 'آيس سبانيش لاتيه منعش مصنوع مع إسبريسو قوي وحليب طازج وحليب مكثف محلى، معزز بمزيج إيطالي خاص، يقدم مثلجاً لتجربة فريدة ولذيذة.', 3),
  (cat_iced, 'Iced Hazelnut Latte', 'آيس هازلنت لاتيه', 'Refreshing iced hazelnut latte made with fresh milk and aromatic coffee, featuring a rich and delicious hazelnut flavor. Served cold with ice for an unforgettable sensory experience.', 'آيس هازلنت لاتيه منعش مصنوع مع الحليب الطازج والقهوة العطرية، بنكهة بندق غنية ولذيذة. يقدم بارداً مع الثلج لتجربة حسية لا تُنسى.', 4),
  (cat_iced, 'Iced Pistachio Latte', 'آيس فستق لاتيه', 'A refreshing iced pistachio latte, rich with luxurious natural pistachio flavor, blended with smooth milk and cold ice for a delightful summer drink experience.', 'آيس فستق لاتيه منعش، غني بنكهة الفستق الطبيعية الفاخرة، مخلوط مع حليب سلس وثلج بارد لتجربة مشروب صيفي ممتعة.', 5),
  (cat_iced, 'Iced Caramel Macchiato', 'آيس كراميل ماكياتو', 'Iced macchiato coffee with a rich and sweet caramel flavor, a touch of vanilla, and layers of frothed milk and dark coffee for a refreshing and delicious experience.', 'قهوة آيس ماكياتو بنكهة كراميل غنية وحلوة، لمسة من الفانيلا، وطبقات من الحليب المخفوق والقهوة الداكنة لتجربة منعشة ولذيذة.', 6),
  (cat_iced, 'Caramel Frappuccino', 'كراميل فرابتشينو', 'Delicious caramel frappuccino made with iced coffee, rich caramel sauce, smooth milk, and topped with whipped cream.', 'كراميل فرابتشينو لذيذ مصنوع مع قهوة مثلجة، صلصة كراميل غنية، حليب سلس، ومغطى بكريمة مخفوقة.', 7),
  (cat_iced, 'Delicious Hazelnut Frappuccino', 'هازلنت فرابتشينو لذيذ', 'The delicious hazelnut Frappuccino is a refreshing drink made with iced coffee and creamy milk, featuring a rich and deep hazelnut flavor. Served with ice and whipped cream.', 'هازلنت فرابتشينو اللذيذ هو مشروب منعش مصنوع مع قهوة مثلجة وحليب كريمي، بنكهة بندق غنية وعميقة. يقدم مع الثلج والكريمة المخفوقة.', 8),
  (cat_iced, 'Iced Mocha', 'آيس موكا', 'A delicious iced mocha combining the rich taste of coffee with luxurious chocolate flavor, with cold milk and ice for a refreshing and enjoyable experience.', 'آيس موكا لذيذ يجمع بين طعم القهوة الغني ونكهة الشوكولاتة الفاخرة، مع حليب بارد وثلج لتجربة منعشة وممتعة.', 9),
  (cat_iced, 'Iced Americano', 'آيس أمريكانو', 'A refreshing iced Americano served cold and rich in caffeine to uplift your mood and give you focus and energy throughout the day.', 'آيس أمريكانو منعش يقدم بارداً وغنياً بالكافيين لرفع معنوياتك ومنحك التركيز والطاقة طوال اليوم.', 10);

  -- ============ MILKSHAKE ============
  INSERT INTO menu_items (category_id, name_en, name_ar, description_en, description_ar, sort_order) VALUES
  (cat_milkshake, 'Lotus Milkshake', 'ميلك شيك لوتس', 'A delicious Lotus milkshake made with luxurious Lotus ice cream, creamy Lotus spread, and cold milk, creating a thick and rich texture, served chilled and refreshing.', 'ميلك شيك لوتس لذيذ مصنوع مع آيس كريم لوتس فاخر، كريمة لوتس، وحليب بارد، يخلق قوام كثيف وغني، يقدم بارداً ومنعشاً.', 1),
  (cat_milkshake, 'Oreo Milkshake', 'ميلك شيك أوريو', 'Delicious and refreshing Oreo milkshake made with premium Oreo ice cream, cold milk, and ice, served chilled with delightful Oreo pieces.', 'ميلك شيك أوريو لذيذ ومنعش مصنوع مع آيس كريم أوريو فاخر، حليب بارد، وثلج، يقدم بارداً مع قطع أوريو لذيذة.', 2),
  (cat_milkshake, 'Nutella Milkshake', 'ميلك شيك نوتيلا', 'A cold and refreshing Nutella milkshake made with the finest Nutella chocolate with cold and iced milk, served iced with a rich and smooth delicious taste.', 'ميلك شيك نوتيلا بارد ومنعش مصنوع من أجود أنواع نوتيلا الشوكولاتة مع الحليب البارد والمثلج يقدم مثلج بطعم غني وسلس لذيذ جداً', 3),
  (cat_milkshake, 'Arabic Ice Cream Milkshake', 'ميلك شيك آيس كريم عربي', 'A refreshing and cold Arabic ice cream milkshake, made from the finest creamy Arabic ice cream blended with rich milk, offering a unique and delicious flavor. Served chilled to give you an enjoyable experience.', 'ميلك شيك آيس كريم عربي منعش وبارد، مصنوع من أجود آيس كريم عربي كريمي مخلوط مع حليب غني، يقدم نكهة فريدة ولذيذة. يقدم بارداً لمنحك تجربة ممتعة.', 4),
  (cat_milkshake, 'Pistachio Milkshake', 'ميلك شيك فستق', 'Delicious pistachio milkshake prepared with fresh milk, premium pistachios, a touch of sugar, and vanilla. Served cold with a smooth creamy foam on top.', 'ميلك شيك فستق لذيذ محضّر مع حليب طازج، فستق فاخر، لمسة سكر، وفانيلا. يقدم بارداً مع رغوة كريمية سلسة على الوجه.', 5);

  -- ============ MOJITOS ============
  INSERT INTO menu_items (category_id, name_en, name_ar, description_en, description_ar, sort_order) VALUES
  (cat_mojitos, 'Large Mojito Soft Drink', 'موهيتو مشروب غازي كبير', 'A refreshing mojito made with fresh mint leaves and fresh lemon juice, served with ice cubes for a smooth, light, and enjoyable cold drink.', 'موهيتو منعش مصنوع مع أوراق النعناع الطازجة وعصير الليمون الطازج، يقدم مع مكعبات الثلج لمشروب بارد سلس وخفيف وممتع.', 1),
  (cat_mojitos, 'Large Mojito Soda', 'موهيتو صودا كبير', 'A refreshing mojito prepared with sparkling soda water, fresh mint leaves, sour lemon, and ice, offering a crisp, refreshing, and vibrant taste.', 'موهيتو منعش محضّر مع ماء الصودا الفوار، أوراق النعناع الطازجة، الليمون الحامض، والثلج، يقدم طعماً منعشاً وحياً.', 2),
  (cat_mojitos, 'Large Energy Mojito', 'موهيتو طاقة كبير', 'A refreshing mojito mixed with an energy drink for an extra boost, combining mint, citrus, and a sparkling invigorating flavor.', 'موهيتو منعش مخلوط مع مشروب طاقة لدفعة إضافية، يجمع بين النعناع والحمضيات ونكهة فوارة منعشة.', 3),
  (cat_mojitos, 'Ice Cup', 'كوب ثلج', 'A perfect ice glass to enjoy your favorite drink cold and refreshing all day. It keeps the beverage cold and adds a touch of freshness.', 'كوب ثلج مثالي للاستمتاع بمشروبك المفضل بارداً ومنعشاً طوال اليوم. يحافظ على المشروب بارداً ويضيف لمسة من الانتعاش.', 4);

  -- ============ COFFEE & HOT DRINKS ============
  INSERT INTO menu_items (category_id, name_en, name_ar, description_en, description_ar, sort_order) VALUES
  (cat_coffee, 'Classic Americano', 'أمريكانو كلاسيك', 'A classic Americano, prepared from rich and strong coffee mixed with hot water to give it a smooth and deep taste with a light foam on top.', 'أمريكانو كلاسيك، محضّر من قهوة غنية وقوية مخلوطة مع ماء ساخن لمنحه طعم سلس وعميق مع رغوة خفيفة على الوجه.', 1),
  (cat_coffee, 'Turkish Coffee on Sand', 'قهوة تركية على الرمل', 'Finely ground Arabica coffee prepared traditionally, brewed and boiled on hot sand to achieve a strong and rich flavor with a distinctive and unique foam, reflecting the authenticity of this Arabic beverage.', 'قهوة عربية مطحونة ناعماً محضّرة تقليدياً، تُغلى على الرمل الساخن لتحقيق نكهة قوية وغنية مع رغوة مميزة وفريدة، تعكس أصالة هذا المشروب العربي.', 2),
  (cat_coffee, 'French Hazelnut Coffee on Sand', 'قهوة فرنسية بالبندق على الرمل', 'Rich French coffee, traditionally prepared on hot sand, flavored with a luxurious roasted hazelnut flavor. It boasts a strong aromatic scent and a warm, deep taste.', 'قهوة فرنسية غنية، محضّرة تقليدياً على الرمل الساخن، بنكهة بندق محمص فاخرة. تتميز برائحة عطرية قوية وطعم دافئ وعميق.', 3),
  (cat_coffee, 'French Macadamia Coffee on Sand', 'قهوة فرنسية بالماكاديميا على الرمل', 'French Macadamia Coffee on Sand. A luxurious coffee on sand with creamy and rich macadamia flavor, offering a smooth and distinctive taste.', 'قهوة فرنسية بالماكاديميا على الرمل. قهوة فاخرة على الرمل بنكهة الماكاديميا الكريمية الغنية، تقدم طعم سلس ومميز.', 4),
  (cat_coffee, '600ml Water', 'ماء 600مل', 'Pure drinking water in 600ml bottles, perfect for quick refreshment and daily hydration, ensuring your health and safety.', 'ماء شرب نقي في عبوات 600مل، مثالي للانتعاش السريع والترطيب اليومي، يضمن صحتك وسلامتك.', 5),
  (cat_coffee, 'Luxury Hazelnut Cappuccino', 'كابتشينو بندق فاخر', 'Luxury cappuccino with rich roasted hazelnut flavor, smooth and creamy milk foam, served hot for an unforgettable professional coffee experience.', 'كابتشينو فاخر بنكهة بندق محمص غنية، رغوة حليب سلسة وكريمية، يقدم ساخناً لتجربة قهوة احترافية لا تُنسى.', 6),
  (cat_coffee, 'Caramel Cappuccino', 'كابتشينو كراميل', 'A luxurious cappuccino with a rich and sweet caramel flavor, topped with smooth and creamy milk foam, served hot to give you an unforgettable coffee experience.', 'كابتشينو فاخر بنكهة كراميل غنية وحلوة، مغطى برغوة حليب سلسة وكريمية، يقدم ساخناً لمنحك تجربة قهوة لا تُنسى.', 7),
  (cat_coffee, 'Karak Tea', 'شاي كرك', 'Rich and distinctive karak tea with fresh milk, blended with aromatic flavors of cinnamon, ginger, cardamom, and a touch of luxurious saffron. A warm drink that combines authenticity and taste.', 'شاي كرك غني ومميز مع حليب طازج، مخلوط بنكهات عطرية من القرفة والزنجبيل والهيل ولمسة من الزعفران الفاخر. مشروب دافئ يجمع بين الأصالة والطعم.', 8),
  (cat_coffee, 'Hot Chocolate', 'شوكولاتة ساخنة', 'Luxury hot chocolate made from the finest Belgian chocolate with rich, creamy milk, topped with smooth foam and grated chocolate.', 'شوكولاتة ساخنة فاخرة مصنوعة من أجود شوكولاتة بلجيكية مع حليب غني كريمي، مغطاة برغوة سلسة وشوكولاتة مبشورة.', 9);

  -- ============ BREAKFAST AND BOWLS ============
  INSERT INTO menu_items (category_id, name_en, name_ar, description_en, description_ar, sort_order) VALUES
  (cat_breakfast, 'Fresh and refreshing fruit salad', 'سلطة فواكه طازجة ومنعشة', 'Enjoy a fresh and refreshing fruit salad, prepared with the finest carefully selected seasonal fruits. Served chilled to give you a delicious and healthy taste experience with every bite.', 'استمتع بسلطة فواكه طازجة ومنعشة، محضّرة بأجود الفواكه الموسمية المختارة بعناية. تقدم باردة لمنحك تجربة طعم لذيذة وصحية مع كل قضمة.', 1),
  (cat_breakfast, 'Firo Breakfast (Fruits and Chocolate)', 'فطور فيرو (فواكه وشوكولاتة)', 'A delicious breakfast combining fresh fruits like strawberries, bananas, kiwi, and apples with a touch of delicious chocolate for an energetic and enjoyable start to the day.', 'فطور لذيذ يجمع بين الفواكه الطازجة مثل الفراولة والموز والكيوي والتفاح مع لمسة من الشوكولاتة اللذيذة لبداية يوم مليئة بالطاقة والمتعة.', 2);

  -- ============ DESSERTS ============
  INSERT INTO menu_items (category_id, name_en, name_ar, description_en, description_ar, sort_order) VALUES
  (cat_desserts, 'Creme Caramel', 'كريم كراميل', 'Luxurious creme caramel, carefully prepared with fresh cream and a delicious golden caramel sauce, served cold with a smooth, sweet taste that melts in your mouth.', 'كريم كراميل فاخر، محضّر بعناية مع قشطة طازجة وصلصة كراميل ذهبية لذيذة، يقدم بارداً بطعم حلو سلس يذوب في الفم.', 1),
  (cat_desserts, 'Vero Cake', 'كيك فيرو', 'Premium Vero Cake prepared with rich chocolate and a smooth creamy layer in our special way, melting in the mouth and leaving an unforgettable delicious taste.', 'كيك فيرو فاخر محضّر مع شوكولاتة غنية وطبقة كريمية سلسة بطريقتنا الخاصة، يذوب في الفم ويترك طعم لذيذ لا يُنسى.', 2),
  (cat_desserts, 'Fero Lava Cake', 'كيك لافا فيرو', 'Luxurious Fero Lava Cake filled with a rich chocolate filling and covered with a smooth chocolate layer, topped with fresh fruit pieces that add a touch of freshness and flavor.', 'كيك لافا فيرو فاخر مليء بحشوة شوكولاتة غنية ومغطى بطبقة شوكولاتة سلسة، مزين بقطع فواكه طازجة تضيف لمسة من الانتعاش والنكهة.', 3);
END $$;